name: Job Artifacts
on: 
  push: 
    paths: 
      - 'job-artifacts/**'
  workflow_dispatch:
  
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: job-artifacts
    steps: 
      - name: Checkout code
        uses: actions/checkout@v3
      - name: display files
        run: ls
      - name: Cache dependencies
        uses: actions/cache@v4
        with: 
          path: ~/.npm
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci 
      - name: Lint code 
        run: npm run lint
      - name: Test code
        run: npm run test 
  build: 
    needs: test 
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: job-artifacts
    outputs: 
      script-file: ${{ steps.publish.outputs.js_filename }} # this is the identifier by which you later will be able to access the output value
      # github actions context value: steps is the context above.
    steps: 
      - name: Checkout code 
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v4
        with: 
          path: ~/.npm
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Build code
        run: npm run build
      - name: Display files
        run: ls
      - name: Publish JS filename
        id: publish
        run: find dist/assets/*.js -type f -execdir echo 'js_filename={}' >> $GITHUB_OUTPUT ';'
      - name: Upload artifacts
        uses: actions/upload-artifact@v4 # read more: https://github.com/actions/upload-artifact
        with: 
          name: dist-files 
          path: ./job-artifacts/dist # path to the folder to upload, can upload multiple folders or files
  deploy: 
    needs: build # only run this job if the build job is successful
    runs-on: ubuntu-latest
    steps: 
      - name: Get build artifacts
        uses: actions/download-artifact@v4 # read more: https://github.com/actions/download-artifact
        with: 
          name: dist-files
      - name: Display files
        run: ls
      - name: Output filename 
        run: echo ${{ needs.build.outputs.script-file }} # this is how you access the output value from the previous job 
        # ${{ }}: dynamic expressions syntax
      - name: Deploy code
        run: echo "Deploying code"